# Generated by Django 6.0.7 on 2026-08-13 06:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly slug.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Course Title')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL slug for the course.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Course Description')),
                ('thumbnail', models.ImageField(blank=True, help_text='Upload an image (JPG, PNG, WEBP).', null=True, upload_to='courses/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Course Thumbnail Image')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='Difficulty Level')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Set 0.00 for free courses.', max_digits=8, verbose_name='Price ($)')),
                ('is_published', models.BooleanField(default=False, help_text='Only published courses will be visible to students.', verbose_name='Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='Course Category')),
                ('teacher', models.ForeignKey(help_text='Must be a user with the Teacher role.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Course Instructor')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
    ]
