# Generated by Django 6.0.7 on 2026-08-19 04:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Lesson Title')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly lesson identifier. Unique per course.', max_length=255)),
                ('description', models.TextField(blank=True, verbose_name='Lesson Description')),
                ('content', models.TextField(blank=True, help_text='Written lesson notes or text material.', verbose_name='Lesson Content')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (e.g. YouTube).', validators=[django.core.validators.URLValidator()], verbose_name='Video URL')),
                ('pdf_file', models.FileField(blank=True, help_text='Upload a PDF document for this lesson.', null=True, upload_to='lessons/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF Document')),
                ('order', models.PositiveIntegerField(default=1, help_text='Position of this lesson within the course.', verbose_name='Lesson Order')),
                ('is_published', models.BooleanField(default=False, help_text='Only published lessons will be visible to students.', verbose_name='Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['course', 'order'],
                'constraints': [models.UniqueConstraint(fields=('course', 'slug'), name='unique_lesson_slug_per_course'), models.UniqueConstraint(fields=('course', 'order'), name='unique_lesson_order_per_course')],
                'unique_together': {('course', 'order')},
            },
        ),
    ]
